version: "3.7"
services:
  demo_db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demoDB
#      MYSQL_USER: user
#      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      demo:

  demo_app:
    image: demo_app:latest
    container_name: demo_app
    hostname: demo_app
    depends_on:
      - demo_db
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://demo_db:3306/demoDB
    networks:
      - demo

networks:
  demo: